### ISSUE TITLE
禁忌搜索有误

### ISSUE THREAD

**Issue by LIU-WEI-git** [kellenf/TSP_collection#1]
移动加入禁忌表的时候应当反向后加入，直接禁忌移动的话就相当于减小了后续搜索的广度

**Comment by LIU-WEI-git** [comment]
抱歉，搞错了，TSP问题移动没有方向性，所以不需要反向

**Comment by LIU-WEI-git** [comment]
抱歉，又错了，你的移动记录方法是下标，而不是具体城市，所以不需要反向禁忌移动。如果是记录交换城市的序号，就可能需要反向，这还跟生成方式和记录顺序有关。总的来说，纸上推演和实践还是有区别的

**Comment by kellenf** [comment]
嗯，如果还有问题可以一起再讨论讨论
