### ISSUE TITLE
PSO

### ISSUE THREAD

**Issue by LucXiong** [kellenf/TSP_collection#3]
PSO.py  Line 118是不是该返回one2, l2? 但是修改之后的最佳值反而更差？
    # 粒子交叉
    def cross(self, cur, best):
        one = cur.copy()
        l = [t for t in range(self.num_city)]
        t = np.random.choice(l,2)
        x = min(t)
        y = max(t)
        cross_part = best[x:y]
        tmp = []
        for t in one:
            if t in cross_part:
                continue
            tmp.append(t)
        # 两种交叉方法
        one = tmp + cross_part
        l1 = self.compute_pathlen(one, self.dis_mat)
        one2 = cross_part + tmp
        l2 = self.compute_pathlen(one2, self.dis_mat)
        if l1<l2:
            return one, l1
        else:
(Line 118)            return one, l2

**Comment by kellenf** [comment]
当时是哪个小返回哪个啊

**Comment by LucXiong** [comment]
> 当时是哪个小返回哪个啊

也就是说该返回one2, l2
我也这样认为，但是当Line118也返回one, l1的时候，PSO优化出来的路径更短
![25e5ec0e5d0d7ba8be9cd68632d100e](https://user-images.githubusercontent.com/55743681/128111791-7879423e-798e-4d6b-846b-264187df715e.png)
![6f664b4e8762588357dfc414576ff06](https://user-images.githubusercontent.com/55743681/128111813-328d67f0-8440-4ed5-bfd8-efcdb13c7cd7.png)

**Comment by kellenf** [comment]
233, 那可能前者局部最优了? 进化算法的随机性有点醉的, 反正你看着改吧, 随机的方式你也可以多试几种
